name: docs

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: '3.7'
      - name: Python Version
        run: python --version
      - name: Gen dummy page
        run: |
          cd docs
          pip install pygments
          python doc-generator.py
      - name: Zip release files
        run: |
          cd docs
          zip -j ribs.zip ../*.py
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
